### ISSUE TITLE
Clarify "captureEvent" parameter and usage

### ISSUE THREAD

**Issue by tordans** [CommandersAct/react-tag-commander#4]
In https://github.com/TagCommander/react-tag-commander/blob/master/README.md#capture-events you write:

>In a controller
`wrapper.captureEvent(eventLabel, htmlElement, data);`
In JSX
`<button className="sm-button green-500" onClick={(event) => this.handle(index, event, item.name)}> + </button>`

Please clarify:
1. what is `eventLabel`
   1. what is this labels purpose?
   2. where do I specify or copy this string from? What are the required steps in the admin UI?
2. what is `htmlElement`
   1. what is this labels purpose?
   2. what are the requirements for the app; it looks like, this should contain the html-element that the click created; which is not always present – can it be blank `''```
3. how does `data` work in the admin UI; what do I need to configure in the admin UI to use this data?

Thanks

**Comment by tordans** [comment]
@TagCommander any news on this?

**Comment by tonylepsie** [comment]
Hello @TagCommander , please answer @tordans , instructions are not clear

**Comment by RomainLK** [comment]
For the trigger event, you can check first the community documentation about the non wrapped function.

Event label is the name of the event, and accessible with `tC.event.name_of_event`. This can de defined at Tag Commanders > Edition > Rules > Triggers > Add Trigger> Custom

htmlElement is a left over from the non wrapped version as the events are usually added on a DOM node. You can either send the button for instance if it's an event on a click, or keep it null. Honestly I'm unsure if there is a use.

Lastly for the data, this is part of the setup. Going from documentation, the consulting team should be able to set it up for you. You should check with your usual consultant

**Comment by thepiwo** [comment]
I will close this for now, feel free to reopen if the issue persists
