### ISSUE TITLE
Wrong version of react-tag-commander in sample app

### ISSUE THREAD

**Issue by fireflyfolio** [CommandersAct/react-tag-commander#56]
Hello,

We have the following error when running the sample app:
...Uncaught TypeError: wrapper.trackPageLoad is not a function...

This is due to the version 1.1.1 of react-tag-commander defined in package.json.
The function trackPageLoad is defined from the version 2.0.0

Could you fix the bug please?

Thanks in advance

**Comment by tmrdlt** [comment]
Hello @fireflyfolio,

thank you for reporting the issue. The version of `tag-commander-wrapper` in the sample app was recently updated. 

Best regards,
Tmrldt
